import {
  extractJsonObject,
  flashcardsSchema,
  quizSchema,
  reviewerSchema,
  safeJsonParse,
} from "@/lib/ai/schemas";
import { getAIPipelineConfig } from "@/lib/ai/config";
import type {
  Flashcard,
  GenerationProvider,
  QuizGenerationInput,
} from "@/lib/ai/types";

type OllamaGenerateResponse = {
  response?: string;
};

async function callOllama(prompt: string) {
  const config = getAIPipelineConfig();
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), config.localTimeoutMs);

  try {
    const response = await fetch(`${config.localBaseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: config.localModel,
        stream: false,
        prompt,
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`OLLAMA_HTTP_${response.status}`);
    }

    const payload = (await response.json()) as OllamaGenerateResponse;
    const raw = String(payload.response || "").trim();

    if (!raw) {
      throw new Error("OLLAMA_EMPTY_RESPONSE");
    }

    return raw;
  } finally {
    clearTimeout(timeout);
  }
}

function parseLocalReviewer(raw: string) {
  const candidate = extractJsonObject(raw);
  const parsed = safeJsonParse<unknown>(candidate);
  const validated = reviewerSchema.safeParse(parsed);

  if (!validated.success) {
    throw new Error("LOCAL_REVIEWER_SCHEMA_INVALID");
  }

  return [
    "Summary:",
    validated.data.summary,
    "",
    "Key Points:",
    ...validated.data.keyPoints.map((value) => `- ${value}`),
  ].join("\n");
}

function parseLocalQuiz(raw: string, input: Omit<QuizGenerationInput, "text">) {
  const candidate = extractJsonObject(raw);
  const parsed = safeJsonParse<unknown>(candidate);
  const validated = quizSchema.safeParse(parsed);

  if (!validated.success) {
    throw new Error("LOCAL_QUIZ_SCHEMA_INVALID");
  }

  const difficulty = input.difficulty || "medium";
  const questionType = input.questionType || "multiple_choice";

  return validated.data.questions
    .slice(0, input.count || 5)
    .map((question, index) => ({
      id: index + 1,
      question: question.question,
      options: question.options,
      answer: question.answer,
      difficulty,
      questionType,
      contextHint: "Generated by local model with structured schema.",
    }));
}

function parseLocalFlashcards(raw: string): Flashcard[] {
  const candidate = extractJsonObject(raw);
  const parsed = safeJsonParse<unknown>(candidate);
  const validated = flashcardsSchema.safeParse(parsed);

  if (!validated.success) {
    throw new Error("LOCAL_FLASHCARDS_SCHEMA_INVALID");
  }

  return validated.data.flashcards;
}

export const localOllamaProvider: GenerationProvider = {
  name: "local-ollama",
  async generateReviewer(context) {
    const prompt = [
      "Return only valid JSON with this shape:",
      '{"summary":"...","keyPoints":["..."]}',
      "Create a concise reviewer for this study text:",
      context.contextText,
    ].join("\n\n");

    const raw = await callOllama(prompt);
    return parseLocalReviewer(raw);
  },
  async generateQuiz(context, input) {
    const prompt = [
      "Return only valid JSON with this shape:",
      '{"questions":[{"question":"...","options":["A","B","C","D"],"answer":"A"}]}',
      `Create ${input.count || 5} ${input.difficulty || "medium"} ${input.questionType || "multiple_choice"} questions from this text:`,
      context.contextText,
    ].join("\n\n");

    const raw = await callOllama(prompt);
    return parseLocalQuiz(raw, input);
  },
  async generateFlashcards(context) {
    const prompt = [
      "Return only valid JSON with this shape:",
      '{"flashcards":[{"front":"...","back":"...","keyword":"..."}]}',
      "Create useful study flashcards from this text:",
      context.contextText,
    ].join("\n\n");

    const raw = await callOllama(prompt);
    return parseLocalFlashcards(raw);
  },
};
